#!/bin/sh
PASS=$1
sudo rm -rf ./LiNUZE.app
sudo rm -rf ./Build/Release-iphoneos/LiNUZE.app
sudo rm -rf ./com.rA9stuff.LiNUZE
sudo rm -rf LiNUZE.zip
xcodebuild -target LiNUZE -xcconfig compile64.xcconfig -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
mv ./build/Debug-iphoneos/LiNUZE.app ./LiNUZE.app
rm -f ./LiNUZE.app/embedded.mobileprovision
mkdir ./com.rA9stuff.LiNUZE
cp -r ./Template/* ./com.rA9stuff.LiNUZE/
mkdir com.rA9stuff.LiNUZE/Applications/
mv LiNUZE.app com.rA9stuff.LiNUZE/Applications/
rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
echo "moving to iPhone"
dpkg-deb -Zgzip -b com.rA9stuff.LiNUZE com.ra9stuff.LiNUZE.deb
rm -rf com.rA9stuff.LiNUZE
